window.CatalogData = {
  vendedorWhatsApp: "56968787862",
  products: [
      // ================= LÍNEA RED =================
      { id: "q01", code: "Q 01", name: "English Pear & Freesia", sub: "Inspirado en Jo Malone", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q02", code: "Q 02", name: "Black Orchid", sub: "Inspirado en Tom Ford", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q03", code: "Q 03", name: "Love Don't Be Shy", sub: "Inspirado en Kilian", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q04", code: "Q 04", name: "Soleil Blanc", sub: "Inspirado en Tom Ford", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q05", code: "Q 05", name: "Baccarat Rouge 540", sub: "Inspirado en MFK", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q06", code: "Q 06", name: "Bianco Latte", sub: "Inspirado en G. Di Toscana", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q07", code: "Q 07", name: "Oriana", sub: "Inspirado en Marly", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q08", code: "Q 08", name: "Attrape-Rêves", sub: "Inspirado en Louis Vuitton", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },
      { id: "q09", code: "Q 09", name: "Bleecker Street", sub: "Inspirado en Bond N°9", cat: "red-black", badge: "RED", fixedSize: "100 ml", price: 26000 },

      // ================= LÍNEA BLACK =================
      { id: "q51", code: "Q 51", name: "Santal 33", sub: "Inspirado en Le Labo", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q52", code: "Q 52", name: "Ombré Leather", sub: "Inspirado en Tom Ford", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q53", code: "Q 53", name: "Silver Mountain Water", sub: "Inspirado en Creed", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q54", code: "Q 54", name: "Aventus", sub: "Inspirado en Creed", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q55", code: "Q 55", name: "Neroli Portofino", sub: "Inspirado en Tom Ford", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q56", code: "Q 56", name: "Born in Roma Uomo", sub: "Inspirado en Valentino", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q57", code: "Q 57", name: "Erba Pura", sub: "Inspirado en Xerjoff", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q58", code: "Q 58", name: "L'Immensité", sub: "Inspirado en Louis Vuitton", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },
      { id: "q59", code: "Q 59", name: "Althaïr", sub: "Inspirado en Parfums de Marly", cat: "red-black", badge: "BLACK", fixedSize: "100 ml", price: 26000 },

      // ================= PERFUMES HOMBRE TRADICIONALES =================
      { id: "h01", code: "H-01", name: "Drakkar Noir", sub: "Guy Laroche / 1982", cat: "hombre", tiered: true, notes: "Fougere Fresco", colors: ["c-fougere"] },
      { id: "h02", code: "H-02", name: "Azzaro Pour Homme", sub: "Azzaro / 1978", cat: "hombre", tiered: true, notes: "Fougere Aromático", colors: ["c-fougere", "c-aromatico"] },
      { id: "h03", code: "H-03", name: "Quorum", sub: "Puig / 1982", cat: "hombre", tiered: true, notes: "Chypre Aromático", colors: ["c-chypre", "c-aromatico"] },
      { id: "h04", code: "H-04", name: "Paco Rabanne", sub: "Paco Rabanne / 1973", cat: "hombre", tiered: true, notes: "Fougere Aromático", colors: ["c-fougere", "c-aromatico"] },
      { id: "h05", code: "H-05", name: "Invictus Platinum", sub: "Paco Rabanne / 2022", cat: "hombre", tiered: true, notes: "Maderoso Aromático", colors: ["c-maderoso", "c-aromatico"] },
      { id: "h06", code: "H-06", name: "Polo Blue Men", sub: "Ralph Lauren / 2002", cat: "hombre", tiered: true, notes: "Maderoso Frutal", colors: ["c-maderoso", "c-frutal"] },
      { id: "h07", code: "H-07", name: "212 Heroes Men", sub: "Carolina Herrera / 2021", cat: "hombre", tiered: true, notes: "Fougere Frutal", colors: ["c-fougere", "c-frutal"] },
      { id: "h08", code: "H-08", name: "Armani Code", sub: "Giorgio Armani / 2004", cat: "hombre", tiered: true, notes: "Maderoso Aromático", colors: ["c-maderoso", "c-aromatico"] },
      { id: "h09", code: "H-09", name: "Tommy", sub: "Tommy Hilfiger / 1995", cat: "hombre", tiered: true, notes: "Maderoso Aromático", colors: ["c-maderoso", "c-aromatico"] },
      { id: "h10", code: "H-10", name: "Carolina Herrera for Men", sub: "Carolina Herrera / 1991", cat: "hombre", tiered: true, notes: "Maderoso Aromático", colors: ["c-maderoso", "c-aromatico"] },
      { id: "h11", code: "H-11", name: "Agua Brava", sub: "Puig / 1968", cat: "hombre", tiered: true, notes: "Fougere Aromático", colors: ["c-fougere", "c-aromatico"] },
      { id: "h12", code: "H-12", name: "Ted Lapidus", sub: "Ted Lapidus / 1978", cat: "hombre", tiered: true, notes: "Chypre Maderoso", colors: ["c-chypre", "c-maderoso"] },
      { id: "h13", code: "H-13", name: "Polo Sport", sub: "Ralph Lauren", cat: "hombre", tiered: true, notes: "Fougere Aromático", colors: ["c-floral", "c-citrico"] },
      { id: "h14", code: "H-14", name: "212 Men", sub: "Carolina Herrera", cat: "hombre", tiered: true, notes: "Maderoso Verde", colors: ["c-floral", "c-aldehidico"] },
      { id: "h15", code: "H-15", name: "Sauvage Elixir", sub: "Christian Dior", cat: "hombre", tiered: true, notes: "Fougere Aromático", colors: ["c-fougere", "c-floral"] },
      { id: "h16", code: "H-16", name: "Stronger With You", sub: "Armani / 2017", cat: "hombre", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "h17", code: "H-17", name: "Burberry Hero", sub: "Burberry / 2021", cat: "hombre", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "h18", code: "H-18", name: "Sauvage", sub: "Christian Dior / 2015", cat: "hombre", tiered: true, notes: "Fougere Maderoso", colors: ["c-fougere", "c-maderoso"] },
      { id: "h19", code: "H-19", name: "Fahrenheit", sub: "Christian Dior / 1988", cat: "hombre", tiered: true, notes: "Maderoso Floral", colors: ["c-maderoso", "c-floral"] },
      { id: "h20", code: "H-20", name: "Acqua di Gio Profondo", sub: "Giorgio Armani / 2020", cat: "hombre", tiered: true, notes: "Cítrico Amaderado", colors: ["c-citrico", "c-maderoso"] },
      { id: "h21", code: "H-21", name: "Elements", sub: "Hugo Boss / 1993", cat: "hombre", tiered: true, notes: "Maderoso Aromático", colors: ["c-maderoso", "c-aromatico"] },
      { id: "h22", code: "H-22", name: "Acqua di Gio", sub: "Giorgio Armani / 1996", cat: "hombre", tiered: true, notes: "Maderoso Cítrico", colors: ["c-maderoso", "c-citrico"] },
      { id: "h23", code: "H-23", name: "Halloween Man", sub: "Jesús Del Pozo", cat: "hombre", tiered: true, notes: "Oriental Maderoso", colors: ["c-oriental", "c-maderoso"] },
      { id: "h24", code: "H-24", name: "Boss", sub: "Hugo Boss / 1998", cat: "hombre", tiered: true, notes: "Oriental Maderoso", colors: ["c-oriental", "c-maderoso"] },
      { id: "h25", code: "H-25", name: "212 VIP Men", sub: "Carolina Herrera / 2011", cat: "hombre", tiered: true, notes: "Oriental Maderoso", colors: ["c-oriental", "c-maderoso"] },
      { id: "h26", code: "H-26", name: "CK One", sub: "Calvin Klein / 1994", cat: "hombre", tiered: true, notes: "Cítrico Fresco", colors: ["c-citrico"] },
      { id: "h27", code: "H-27", name: "XS Black", sub: "Paco Rabanne / 2005", cat: "hombre", tiered: true, notes: "Maderoso Frutal", colors: ["c-maderoso", "c-frutal"] },
      { id: "h28", code: "H-28", name: "Eros", sub: "Versace / 2012", cat: "hombre", tiered: true, notes: "Oriental Maderoso", colors: ["c-oriental", "c-maderoso"] },
      { id: "h29", code: "H-29", name: "One Million Intense", sub: "Paco Rabanne / 2013", cat: "hombre", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "h30", code: "H-30", name: "Light Blue Homme", sub: "Dolce & Gabbana / 2007", cat: "hombre", tiered: true, notes: "Maderoso Aromático", colors: ["c-maderoso", "c-aromatico"] },
      { id: "h31", code: "H-31", name: "Polo Black", sub: "Ralph Lauren / 2007", cat: "hombre", tiered: true, notes: "Fougere Maderoso", colors: ["c-fougere", "c-maderoso"] },
      { id: "h32", code: "H-32", name: "Y Edt", sub: "Yves Saint Laurent / 2021", cat: "hombre", tiered: true, notes: "Fougere Maderoso", colors: ["c-fougere", "c-maderoso"] },
      { id: "h33", code: "H-33", name: "Le Beau", sub: "Jean Paul Gaultier / 2019", cat: "hombre", tiered: true, notes: "Fougere Oriental", colors: ["c-fougere", "c-oriental"] },
      { id: "h34", code: "H-34", name: "One Million", sub: "Paco Rabanne / 2008", cat: "hombre", tiered: true, notes: "Maderoso Frutal", colors: ["c-maderoso", "c-frutal"] },
      { id: "h35", code: "H-35", name: "MYSLF", sub: "Yves Saint Laurent / 2023", cat: "hombre", tiered: true, notes: "Amaderado Frutal", colors: ["c-maderoso", "c-frutal"] },
      { id: "h36", code: "H-36", name: "Invictus", sub: "Paco Rabanne / 2013", cat: "hombre", tiered: true, notes: "Fougere Oriental", colors: ["c-fougere", "c-oriental"] },
      { id: "h37", code: "H-37", name: "Acqua di Gio Absolu", sub: "Giorgio Armani / 2018", cat: "hombre", tiered: true, notes: "Maderoso Cítrico", colors: ["c-maderoso", "c-citrico"] },
      { id: "h38", code: "H-38", name: "Polo Red", sub: "Ralph Lauren / 2013", cat: "hombre", tiered: true, notes: "Fougere Oriental", colors: ["c-fougere", "c-oriental"] },
      { id: "h39", code: "H-39", name: "Gucci Guilty", sub: "Gucci / 2011", cat: "hombre", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "h40", code: "H-40", name: "212 VIP Black", sub: "Carolina Herrera / 2017", cat: "hombre", tiered: true, notes: "Fougere Oriental", colors: ["c-fougere", "c-oriental"] },
      { id: "h41", code: "H-41", name: "Bleu de Chanel", sub: "Chanel / 2010", cat: "hombre", tiered: true, notes: "Maderoso Cítrico", colors: ["c-maderoso", "c-citrico"] },
      { id: "h42", code: "H-42", name: "Stronger With You Intensely", sub: "Armani / 2019", cat: "hombre", tiered: true, notes: "Oriental Maderoso (Nuevo)", colors: ["c-oriental", "c-maderoso"] },
      { id: "h43", code: "H-43", name: "Bad Boy", sub: "Carolina Herrera / 2018", cat: "hombre", tiered: true, notes: "Oriental Especiado (Nuevo)", colors: ["c-oriental", "c-especiado"] },
      { id: "h44", code: "H-44", name: "Phantom", sub: "Paco Rabanne / 2021", cat: "hombre", tiered: true, notes: "Fougere Aromático (Nuevo)", colors: ["c-fougere", "c-aromatico"] },
      { id: "h45", code: "H-45", name: "212 VIP Black Elixir", sub: "Carolina Herrera / 2025", cat: "hombre", tiered: true, notes: "Fougere Oriental", colors: ["c-fougere", "c-oriental"] },

      // ================= PERFUMES MUJER TRADICIONALES =================
      { id: "f01", code: "F-01", name: "Paloma Picasso", sub: "Paloma Picasso / 1984", cat: "mujer", tiered: true, notes: "Chypre Floral", colors: ["c-chypre", "c-floral"] },
      { id: "f02", code: "F-02", name: "Poison", sub: "Christian Dior / 1985", cat: "mujer", tiered: true, notes: "Floral Especiado", colors: ["c-floral", "c-especiado"] },
      { id: "f03", code: "F-03", name: "Oscar de la Renta", sub: "Oscar de la Renta / 1976", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f04", code: "F-04", name: "Angel", sub: "Thierry Mugler / 1992", cat: "mujer", tiered: true, notes: "Floral Almizclado / Oriental Mad.", colors: ["c-oriental", "c-maderoso"] },
      { id: "f05", code: "F-05", name: "Chanel Nº 5", sub: "Chanel / 1921", cat: "mujer", tiered: true, notes: "Floral Aldehídico", colors: ["c-floral", "c-aldehidico"] },
      { id: "f06", code: "F-06", name: "212 VIP Rosé", sub: "Carolina Herrera / 2014", cat: "mujer", tiered: true, notes: "Chypre Frutal", colors: ["c-chypre", "c-frutal"] },
      { id: "f07", code: "F-07", name: "Ralph", sub: "Ralph Lauren / 2000", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f08", code: "F-08", name: "Paradoxe", sub: "Prada / 2022", cat: "mujer", tiered: true, notes: "Oriental Floral / Maderoso", colors: ["c-oriental", "c-maderoso"] },
      { id: "f09", code: "F-09", name: "Trésor", sub: "Lancôme / 1993", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f10", code: "F-10", name: "Coco Mademoiselle", sub: "Chanel / 2002", cat: "mujer", tiered: true, notes: "Chypre Frutal", colors: ["c-chypre", "c-frutal"] },
      { id: "f11", code: "F-11", name: "Coco Chanel", sub: "Chanel / 1984", cat: "mujer", tiered: true, notes: "Chypre Frutal", colors: ["c-chypre", "c-frutal"] },
      { id: "f12", code: "F-12", name: "Black Opium", sub: "Yves Saint Laurent / 2017", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f13", code: "F-13", name: "212 Heroes for Her", sub: "Carolina Herrera / 2021", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f14", code: "F-14", name: "CH", sub: "Carolina Herrera / 2007", cat: "mujer", tiered: true, notes: "Oriental Cítrico", colors: ["c-oriental", "c-citrico"] },
      { id: "f15", code: "F-15", name: "Lolita Lempicka", sub: "Lolita Lempicka / 1997", cat: "mujer", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "f16", code: "F-16", name: "Anais-Anais", sub: "Cacharel / 1978", cat: "mujer", tiered: true, notes: "Floral Fresco", colors: ["c-floral"] },
      { id: "f17", code: "F-17", name: "O de Lancôme", sub: "Lancôme / 1965", cat: "mujer", tiered: true, notes: "Cítrico Chypre / Floral", colors: ["c-citrico", "c-floral"] },
      { id: "f18", code: "F-18", name: "Carolina Herrera", sub: "Carolina Herrera / 1978", cat: "mujer", tiered: true, notes: "Floral Floral", colors: ["c-floral"] },
      { id: "f19", code: "F-19", name: "La Bomba", sub: "CH / 2025", cat: "mujer", tiered: true, notes: "Oriental Floral", colors: ["c-oriental", "c-floral"] },
      { id: "f20", code: "F-20", name: "Eternity", sub: "Calvin Klein / 1988", cat: "mujer", tiered: true, notes: "Floral Floral", colors: ["c-floral"] },
      { id: "f21", code: "F-21", name: "Organza", sub: "Givenchy / 1996", cat: "mujer", tiered: true, notes: "Floral Especiado", colors: ["c-floral", "c-especiado"] },
      { id: "f22", code: "F-22", name: "Woman", sub: "Ralph Lauren / 2017", cat: "mujer", tiered: true, notes: "Floral Maderoso", colors: ["c-floral", "c-maderoso"] },
      { id: "f23", code: "F-23", name: "My Way", sub: "Giorgio Armani / 2020", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f24", code: "F-24", name: "Bloom", sub: "Gucci / 2017", cat: "mujer", tiered: true, notes: "Floral Maderoso", colors: ["c-floral", "c-maderoso"] },
      { id: "f25", code: "F-25", name: "Burberry Her", sub: "Burberry / 2018", cat: "mujer", tiered: true, notes: "Floral Frutal Ambarado", colors: ["c-floral", "c-frutal"] },
      { id: "f26", code: "F-26", name: "Paris", sub: "Yves Saint Laurent / 1983", cat: "mujer", tiered: true, notes: "Floral Floral", colors: ["c-floral"] },
      { id: "f27", code: "F-27", name: "Be Delicious", sub: "Donna Karan / 2004", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f28", code: "F-28", name: "CK One", sub: "Calvin Klein / 1994", cat: "mujer", tiered: true, notes: "Cítrico Maderoso", colors: ["c-citrico", "c-maderoso"] },
      { id: "f29", code: "F-29", name: "212", sub: "Carolina Herrera / 1997", cat: "mujer", tiered: true, notes: "Floral Floral", colors: ["c-floral"] },
      { id: "f30", code: "F-30", name: "Devotion", sub: "Dolce & Gabbana / 2023", cat: "mujer", tiered: true, notes: "Cítrico Gourmand", colors: ["c-citrico"] },
      { id: "f31", code: "F-31", name: "Eden", sub: "Cacharel / 1994", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f32", code: "F-32", name: "Escape", sub: "Calvin Klein / 1991", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f33", code: "F-33", name: "La Vida es Bella Intense", sub: "Lancôme / 2015", cat: "mujer", tiered: true, notes: "Oriental Floral", colors: ["c-oriental", "c-floral"] },
      { id: "f34", code: "F-34", name: "Lady Million Empire", sub: "Paco Rabanne / 2019", cat: "mujer", tiered: true, notes: "Chypre Floral", colors: ["c-chypre", "c-floral"] },
      { id: "f35", code: "F-35", name: "Flower", sub: "Kenzo / 2000", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f36", code: "F-36", name: "Tommy Girl", sub: "Tommy Hilfiger / 1996", cat: "mujer", tiered: true, notes: "Floral Verde", colors: ["c-floral", "c-verde"] },
      { id: "f37", code: "F-37", name: "XS Black Woman", sub: "Paco Rabanne / 2007", cat: "mujer", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "f38", code: "F-38", name: "J'Adore", sub: "Christian Dior / 1999", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f39", code: "F-39", name: "Boss Woman", sub: "Hugo Boss / 2000", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f40", code: "F-40", name: "Amor Amor", sub: "Cacharel / 2003", cat: "mujer", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "f41", code: "F-41", name: "Can Can", sub: "Paris Hilton / 2007", cat: "mujer", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "f42", code: "F-42", name: "Scandal", sub: "Jean Paul Gaultier / 2017", cat: "mujer", tiered: true, notes: "Oriental Floral", colors: ["c-oriental", "c-floral"] },
      { id: "f43", code: "F-43", name: "Good Girl", sub: "Carolina Herrera / 2016", cat: "mujer", tiered: true, notes: "Oriental Floral", colors: ["c-oriental", "c-floral"] },
      { id: "f44", code: "F-44", name: "Olympéa", sub: "Paco Rabanne / 2015", cat: "mujer", tiered: true, notes: "Oriental Floral", colors: ["c-oriental", "c-floral"] },
      { id: "f45", code: "F-45", name: "Halloween", sub: "Jesús Del Pozo / 1997", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f46", code: "F-46", name: "212 Sexy", sub: "Carolina Herrera / 2004", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f47", code: "F-47", name: "La Vida es Bella Rosé", sub: "Lancôme / 2019", cat: "mujer", tiered: true, notes: "Floral Chypre", colors: ["c-floral", "c-chypre"] },
      { id: "f48", code: "F-48", name: "Duende", sub: "Jesús Del Pozo / 1996", cat: "mujer", tiered: true, notes: "Floral Verde", colors: ["c-floral", "c-verde"] },
      { id: "f49", code: "F-49", name: "Nina", sub: "Nina Ricci / 2006", cat: "mujer", tiered: true, notes: "Oriental Frutal", colors: ["c-oriental", "c-frutal"] },
      { id: "f50", code: "F-50", name: "Light Blue", sub: "Dolce & Gabbana / 2001", cat: "mujer", tiered: true, notes: "Cítrico Maderoso", colors: ["c-citrico", "c-maderoso"] },
      { id: "f51", code: "F-51", name: "Si", sub: "Armani / 2013", cat: "mujer", tiered: true, notes: "Chypre Frutal", colors: ["c-chypre", "c-frutal"] },
      { id: "f52", code: "F-52", name: "Ultraviolet", sub: "Paco Rabanne / 1999", cat: "mujer", tiered: true, notes: "Floral Verde", colors: ["c-floral", "c-verde"] },
      { id: "f53", code: "F-53", name: "Euphoria", sub: "Calvin Klein / 2005", cat: "mujer", tiered: true, notes: "Oriental Maderoso", colors: ["c-oriental", "c-maderoso"] },
      { id: "f54", code: "F-54", name: "Lady Million", sub: "Paco Rabanne / 2010", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f55", code: "F-55", name: "212 VIP", sub: "Carolina Herrera / 2010", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f56", code: "F-56", name: "Miss Dior", sub: "Christian Dior / 2020", cat: "mujer", tiered: true, notes: "Chypre Floral", colors: ["c-chypre", "c-floral"] },
      { id: "f57", code: "F-57", name: "La Vida es Bella", sub: "Lancôme / 2012", cat: "mujer", tiered: true, notes: "Chypre Oriental", colors: ["c-chypre", "c-oriental"] },
      { id: "f58", code: "F-58", name: "Libre", sub: "Yves Saint Laurent / 2019", cat: "mujer", tiered: true, notes: "Oriental Floral", colors: ["c-oriental", "c-floral"] },
      { id: "f59", code: "F-59", name: "Idôle", sub: "Lancôme / 2019", cat: "mujer", tiered: true, notes: "Chypre Floral", colors: ["c-chypre", "c-floral"] },
      { id: "f60", code: "F-60", name: "Aqua di Gioia", sub: "Armani / 2010", cat: "mujer", tiered: true, notes: "Floral Verde", colors: ["c-floral", "c-verde"] },
      { id: "f61", code: "F-61", name: "La Vida es Bella L'Elixir", sub: "Lancôme / 2024", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f62", code: "F-62", name: "Dolce", sub: "Dolce & Gabbana / 2014", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },
      { id: "f63", code: "F-63", name: "Live Irrésistible", sub: "Givenchy / 2015", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f64", code: "F-64", name: "La Nuit Trésor", sub: "Lancôme / 2015", cat: "mujer", tiered: true, notes: "Floral Oriental", colors: ["c-floral", "c-oriental"] },
      { id: "f65", code: "F-65", name: "Fame", sub: "Paco Rabanne / 2022", cat: "mujer", tiered: true, notes: "Floral Maderoso", colors: ["c-floral", "c-maderoso"] },
      { id: "f66", code: "F-66", name: "Very Good Girl", sub: "Carolina Herrera / 2021", cat: "mujer", tiered: true, notes: "Floral Frutal", colors: ["c-floral", "c-frutal"] },

      // ================= LÍNEA TEEN =================
      { id: "j00", code: "J00", name: "Cloud", sub: "Ariana Grande", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j01", code: "J01", name: "Fantasy", sub: "Britney Spears", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j02", code: "J02", name: "Selena", sub: "Selena Gomez", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j03", code: "J03", name: "Bombshell", sub: "Victoria's Secret", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j04", code: "J04", name: "Thank U, Next", sub: "Ariana Grande", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j05", code: "J05", name: "Meow", sub: "Katy Perry", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j06", code: "J06", name: "Sweet Like Candy", sub: "Ariana Grande", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j07", code: "J07", name: "Legacy", sub: "Cristiano Ronaldo", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j08", code: "J08", name: "Spirit of the Brave", sub: "Neymar Diesel", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },
      { id: "j09", code: "J09", name: "Invictus Aqua", sub: "Paco Rabanne", cat: "teen", badge: "TEEN", fixedSize: "50 ml", price: 8000 },

      // ================= COLONIAS S-400 HOMBRE =================
      { id: "s100", code: "S100", name: "Phantom", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s101", code: "S101", name: "Azzaro", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s102", code: "S102", name: "Sauvage", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s103", code: "S103", name: "Tommy", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s104", code: "S104", name: "Paco Rabanne", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s105", code: "S105", name: "Carolina Herrera", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s106", code: "S106", name: "Agua Brava", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s107", code: "S107", name: "One Million", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s108", code: "S108", name: "Hugo Boss Men", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s109", code: "S109", name: "Polo Sport", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s110", code: "S110", name: "212 VIP Men", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s111", code: "S111", name: "XS Black Men", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s112", code: "S112", name: "Acqua di Gio", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s113", code: "S113", name: "212 For Men", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s114", code: "S114", name: "Invictus", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s115", code: "S115", name: "Polo Blue Men", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s116", code: "S116", name: "Polo Red", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s117", code: "S117", name: "Bad Boy", sub: "Colonia Corporal", cat: "colonia-h", badge: "400 ML", fixedSize: "400 ml", price: 6000 },

      // ================= COLONIAS S-400 MUJER =================
      { id: "s01", code: "S01", name: "Woman", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s02", code: "S02", name: "Oscar de la Renta", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s03", code: "S03", name: "Chanel Nº 5", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s04", code: "S04", name: "Tresor", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s05", code: "S05", name: "Carolina Herrera", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s06", code: "S06", name: "212 Heroes Woman", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s07", code: "S07", name: "Anais Anais", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s08", code: "S08", name: "O de Lancome", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s09", code: "S09", name: "212 Carolina Herrera", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s10", code: "S10", name: "Eden", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s11", code: "S11", name: "Can Can", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s12", code: "S12", name: "Olympea", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s13", code: "S13", name: "C.K. One", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s14", code: "S14", name: "J'Adore", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s15", code: "S15", name: "Nina", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s16", code: "S16", name: "Ralph", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s17", code: "S17", name: "Be Delicious", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s18", code: "S18", name: "Lolita Lempicka", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s19", code: "S19", name: "La Nuit Tresor", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s20", code: "S20", name: "Tommy Girl", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s21", code: "S21", name: "212 VIP", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s22", code: "S22", name: "Amor Amor", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s23", code: "S23", name: "Halloween", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s24", code: "S24", name: "212 Sexy", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s25", code: "S25", name: "Light Blue Woman", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s26", code: "S26", name: "Acqua di Gioia", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s27", code: "S27", name: "La Vida es Bella", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s28", code: "S28", name: "Good Girl", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s29", code: "S29", name: "My Way (G. Armani)", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },
      { id: "s30", code: "S30", name: "212 VIP Rosé", sub: "Colonia Corporal", cat: "colonia-m", badge: "400 ML", fixedSize: "400 ml", price: 6000 },

      // ================= SPLASH =================
      { id: "splash", code: "SPLASH", name: "Colonia Splash", sub: "Explosión cítrica-frutal", cat: "splash", badge: "500 ML", fixedSize: "500 ml", price: 6600, notes: "Explosión cítrica-frutal", colors: ["c-citrico", "c-frutal"] }
    ],
  standardPrices: {
      "100ml": 17000,
      "50ml": 11000,
      "20ml": 6500
    }
};
